# SPDX-FileCopyrightText: 2024 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "lookpoint_firmware"
version = "0.1.0"
authors = ["Derek Sauer <dereksauer.ca@gmail.com>"]
edition = "2021"
rust-version = "1.80"
description = "Firmware for the Lookpoint head tracking device"
documentation = "https://github.com/dereksauer/lookpoint-firmware"
readme = "README.md"
repository = "https://github.com/dereksauer/lookpoint-firmware"
license = "GPL-3.0-only"

[[bin]]
name = "lookpoint_firmware"
harness = false

[dependencies]
embassy-executor = { version = "0.7", features = [
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "nightly",
  "defmt",
] }
embassy-nrf = { version = "0.3", features = [
  "nrf52840",
  "gpiote",
  "time",
  "time-driver-rtc1",
  "unstable-pac",
  "defmt",
] }
embassy-time = { version = "0.4", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-sync = { version = "0.6.2", features = ["defmt"] }

nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", branch = "master", features = [
  "nrf52840",
  "s113",
  "ble-peripheral",
  "critical-section",
  "critical-section-impl",
  "defmt",
] }

cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = { version = "0.7.5", features = ["device"] }

defmt = "0.3.9"
defmt-rtt = "0.4.1"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }

# Development builds (cargo build)
[profile.dev]
opt-level = 1
debug = "full"
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256

# Release builds (cargo build --release)
[profile.release]
opt-level = 's'
debug = "full"
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

# Debug profile dependencies override
[profile.dev.package."*"]
opt-level = 1
debug = "full"
debug-assertions = true
overflow-checks = true
incremental = true
codegen-units = 256

# Release profile dependencies override
[profile.release.package."*"]
opt-level = 's'
debug = "full"
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
