# SPDX-FileCopyrightText: 2024 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-only

# Using the `nightly` toolchain so that `embassy-executor` 
# can statically allocate tasks at compile time.
[toolchain]
channel = "nightly"
profile = "default"
components = ["llvm-tools"]
targets = ["thumbv7em-none-eabihf"]
