# SPDX-FileCopyrightText: 2025 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-or-later

# We're using the nightly features of embassy-executor and static_cell
[toolchain]
channel = "stable"
components = ["rust-src", "rustfmt", "llvm-tools"]
targets = ["thumbv7em-none-eabihf"]
