# SPDX-FileCopyrightText: 2024 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Only options that differ from defaults are listed.

# Some `rustfmt` options we want to use are considered unstable 
# and only available in nightly toolchains.
unstable_features = true

# Stable configuration options.
edition = "2024"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable configuration options.
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
wrap_comments = true
