# SPDX-FileCopyrightText: 2024 Derek Sauer
#
# SPDX-License-Identifier: GPL-3.0-or-later

# The Arduino Nano 33 BLE Rev2 has a Cortex-M4 chip with FPU
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA --protocol swd"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
